[versions]
dependency-updates = "0.54.0"
sonarqube = "7.3.1.8318"
checkstyle = "10.21.4"
picocli = "4.7.7"
junit-jupiter = "5.14.1"
jackson = "2.22.0"

[libraries]
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }

[plugins]
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "dependency-updates" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
